name: build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "5 4 * * 0"

env:
  IMAGE_NAME: batteries

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          config: .github/buildkitd.toml

      - name: Build
        uses: docker/build-push-action@v3
        with:
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64, linux/arm64
          # FIXME: In case of a breaking change, we would need to split this up, so that we can
          # also build older images with a newer base layer.
          tags: "ghcr.io/${{ github.actor }}/${{ env.IMAGE_NAME }}:latest, ghcr.io/${{ github.actor }}/${{ env.IMAGE_NAME }}:1, ghcr.io/${{ github.actor }}/${{ env.IMAGE_NAME }}:1.0, ghcr.io/${{ github.actor }}/${{ env.IMAGE_NAME }}:1.0.0"
